Improve `get_native_model_url` mode handling
In Django 2.2 there were some updates to sites framework:
https://github.com/django/django/commit/a9f5652113f0721a7066e359ae28d14692ea3c47

Which led to changed model dict (includes `admin_url` and `add_url` by default).
This breaks with django-suit 0.2.26 because of the way it handles model dictionary in `get_native_model_url`.
In short: it does expect dict _to not return_ `admin_url` and have a fallback for it, but if we do have `admin_url=None` in dict, it uses it.

That ends up with `AttributeError: 'NoneType' object has no attribute 'rstrip'`:

```
old_model_dict = {'name': 'Items', 'object_name': 'Item', 'perms': {'add': True, 'change': False, 'delete': False, 'view': False}, 'admin_url': None, 'add_url': '/admin/items/item/add/'}
new_model_dict = {'name': 'Items', 'object_name': 'Item', 'perms': {'add': True, 'change': False, 'delete': False, 'view': False}, 'admin_url': None, 'add_url': '/admin/items/item/add/'}

url_parts = self.get_native_model_url(model).rstrip('/').split('/')
```